<?php
/**
 * Plugin Name: Chuyển hướng 301 sang giasu.ai.vn
 * Description: Tự động chuyển hướng các bài viết từ o2.edu.vn sang giasu.ai.vn bằng mã 301 chuẩn SEO.
 * Version: 1.135
 */

add_action('template_redirect', function() {
    $redirects = [
        '/100-cau-ly-thuyet-dem-hoa-huu-co-lop-12-thi-tn-thpt/' => 'https://giasu.ai.vn/bai-viet/100-cau-ly-thuyet-dem-hoa-huu-co-lop-12-thi-tn-thpt.html',
        '/1000-tu-vung-hsk-4-phien-ban-moi/' => 'https://giasu.ai.vn/bai-viet/1000-tu-vung-hsk-4-phien-ban-moi.html',
        '/1000-tu-vung-hsk-5-phien-ban-moi/' => 'https://giasu.ai.vn/bai-viet/1000-tu-vung-hsk-5-phien-ban-moi.html',
        '/1100-tu-vung-hsk-6-phien-ban-moi/' => 'https://giasu.ai.vn/bai-viet/1100-tu-vung-hsk-6-phien-ban-moi.html',
        '/138-cau-hoi-trac-nghiem-python/' => 'https://giasu.ai.vn/bai-viet/138-cau-hoi-trac-nghiem-python.html',
        '/15-cuon-sach-hoc-python-mien-phi/' => 'https://giasu.ai.vn/bai-viet/15-cuon-sach-hoc-python-mien-phi.html',
        '/150-tu-vung-hsk-1-cho-nguoi-moi-bat-dau/' => 'https://giasu.ai.vn/bai-viet/150-tu-vung-hsk-1-cho-nguoi-moi-bat-dau.html',
        '/200-cau-ly-thuyet-dem-hoa-hoc-lop-12-co-dap-an/' => 'https://giasu.ai.vn/bai-viet/200-cau-ly-thuyet-dem-hoa-hoc-lop-12-co-dap-an.html',
        '/2000-chu-kanji-thong-dung-nhat/' => 'https://giasu.ai.vn/bai-viet/2000-chu-kanji-thong-dung-nhat.html',
        '/214-bo-thu-han-ngu/' => 'https://giasu.ai.vn/bai-viet/214-bo-thu-han-ngu.html',
        '/300-tu-vung-hsk-2-phien-ban-cu/' => 'https://giasu.ai.vn/bai-viet/300-tu-vung-hsk-2-phien-ban-cu.html',
        '/50-bai-tap-lap-trinh-scratch/' => 'https://giasu.ai.vn/bai-viet/50-bai-tap-lap-trinh-scratch.html',
        '/50-bo-thu-thuong-dung-pdf/' => 'https://giasu.ai.vn/bai-viet/50-bo-thu-thuong-dung-pdf.html',
        '/5615-tu-vung-hsk-7-tu-vung-hsk-8-tu-vung-hsk-9-moi-nhat/' => 'https://giasu.ai.vn/bai-viet/5615-tu-vung-hsk-7-tu-vung-hsk-8-tu-vung-hsk-9-moi-nhat.html',
        '/700-tu-vung-hsk-2-phien-ban-moi/' => 'https://giasu.ai.vn/bai-viet/700-tu-vung-hsk-2-phien-ban-moi.html',
        '/900-tu-vung-hsk-3-phien-ban-moi/' => 'https://giasu.ai.vn/bai-viet/900-tu-vung-hsk-3-phien-ban-moi.html',
        '/bai-tap-bien-ngau-nhien-va-luat-phan-phoi-xac-suat/' => 'https://giasu.ai.vn/bai-viet/bai-tap-bien-ngau-nhien-va-luat-phan-phoi-xac-suat.html',
        '/bai-tap-phan-ung-tao-muoi-amoni/' => 'https://giasu.ai.vn/bai-viet/bai-tap-phan-ung-tao-muoi-amoni.html',
        '/bai-tap-python-co-ban-co-loi-giai/' => 'https://giasu.ai.vn/bai-viet/bai-tap-python-co-ban-co-loi-giai.html',
        '/bai-tap-python-co-ban-lop-10/' => 'https://giasu.ai.vn/bai-viet/bai-tap-python-co-ban-lop-10.html',
        '/bai-tap-thong-ke-toan-12-ctst/' => 'https://giasu.ai.vn/bai-viet/bai-tap-thong-ke-toan-12-ctst.html',
        '/bai-toan-cau-ca-dirac/' => 'https://giasu.ai.vn/bai-viet/bai-toan-cau-ca-dirac.html',
        '/bai-toan-co2-so2-tac-dung-voi-dung-dich-kiem-co-loi-giai-chi-tiet/' => 'https://giasu.ai.vn/bai-viet/bai-toan-co2-so2-tac-dung-voi-dung-dich-kiem-co-loi-giai-chi-tiet.html',
        '/bai-toan-do-thi-co-ban-trong-hoa-hoc-co-loi-giai-chi-tiet/' => 'https://giasu.ai.vn/bai-viet/bai-toan-do-thi-co-ban-trong-hoa-hoc-co-loi-giai-chi-tiet.html',
        '/bai-toan-do-thi-nang-cao/' => 'https://giasu.ai.vn/bai-viet/bai-toan-do-thi-nang-cao.html',
        '/bai-toan-nang-luong-hoa-hoc-dot-chay-nhien-lieu/' => 'https://giasu.ai.vn/bai-viet/bai-toan-nang-luong-hoa-hoc-dot-chay-nhien-lieu.html',
        '/bai-toan-nhiet-nhom-co-loi-giai-chi-tiet/' => 'https://giasu.ai.vn/bai-viet/bai-toan-nhiet-nhom-co-loi-giai-chi-tiet.html',
        '/bang-ky-tu-dac-biet-thuong-dung/' => 'https://giasu.ai.vn/bai-viet/bang-ky-tu-dac-biet-thuong-dung.html',
        '/bien-luan-cong-thuc-cau-tao-etse-co-loi-giai-chi-tiet/' => 'https://giasu.ai.vn/bai-viet/bien-luan-cong-thuc-cau-tao-etse-co-loi-giai-chi-tiet.html',
        '/bien-luan-cong-thuc-muoi-amoni-huu-co-day-du-chi-tiet/' => 'https://giasu.ai.vn/bai-viet/bien-luan-cong-thuc-muoi-amoni-huu-co-day-du-chi-tiet.html',
        '/binh-am-la-gi-cach-doc-pinyin-tieng-trung/' => 'https://giasu.ai.vn/bai-viet/binh-am-la-gi-cach-doc-pinyin-tieng-trung.html',
        '/bo-de-thi-van-tac-pham-dat-nuoc/' => 'https://giasu.ai.vn/bai-viet/bo-de-thi-van-tac-pham-dat-nuoc.html',
        '/bo-go-tieng-viet-cho-mac/' => 'https://giasu.ai.vn/bai-viet/bo-go-tieng-viet-cho-mac.html',
        '/cac-bai-tho-van-trong-sgk-tieu-hoc-cu/' => 'https://giasu.ai.vn/bai-viet/cac-bai-tho-van-trong-sgk-tieu-hoc-cu.html',
        '/cac-bang-don-vi-do-lop-5/' => 'https://giasu.ai.vn/bai-viet/cac-bang-don-vi-do-lop-5.html',
        '/cac-bieu-hien-cua-nang-luc-toan-hoc/' => 'https://giasu.ai.vn/bai-viet/cac-bieu-hien-cua-nang-luc-toan-hoc.html',
        '/cac-phep-toan-trong-python/' => 'https://giasu.ai.vn/bai-viet/cac-phep-toan-trong-python.html',
        '/cac-thu-tuc-vao-ra-du-lieu-co-ban-trong-python/' => 'https://giasu.ai.vn/bai-viet/cac-thu-tuc-vao-ra-du-lieu-co-ban-trong-python.html',
        '/cac-tu-khoa-trong-python/' => 'https://giasu.ai.vn/bai-viet/cac-tu-khoa-trong-python.html',
        '/cach-chung-minh-duong-thang-vuong-goc-voi-mat-phang/' => 'https://giasu.ai.vn/bai-viet/cach-chung-minh-duong-thang-vuong-goc-voi-mat-phang.html',
        '/cach-chung-minh-hai-mat-phang-song-song/' => 'https://giasu.ai.vn/bai-viet/cach-chung-minh-hai-mat-phang-song-song.html',
        '/cach-giai-rubic-2x2/' => 'https://giasu.ai.vn/bai-viet/cach-giai-rubic-2x2.html',
        '/cach-giai-rubik-3x3-don-gian-nhat/' => 'https://giasu.ai.vn/bai-viet/cach-giai-rubik-3x3-don-gian-nhat.html',
        '/cach-nho-50-bo-thu-thuong-dung/' => 'https://giasu.ai.vn/bai-viet/cach-nho-50-bo-thu-thuong-dung.html',
        '/cach-nho-bo-thu-tieng-trung/' => 'https://giasu.ai.vn/bai-viet/cach-nho-bo-thu-tieng-trung.html',
        '/cach-nho-cac-bo-thu-trong-tieng-trung/' => 'https://giasu.ai.vn/bai-viet/cach-nho-cac-bo-thu-trong-tieng-trung.html',
        '/cach-tim-giao-tuyen-cua-hai-mat-phang/' => 'https://giasu.ai.vn/bai-viet/cach-tim-giao-tuyen-cua-hai-mat-phang.html',
        '/cach-tinh-goc-giua-duong-thang-va-mat-phang-lop-11/' => 'https://giasu.ai.vn/bai-viet/cach-tinh-goc-giua-duong-thang-va-mat-phang-lop-11.html',
        '/cach-tinh-goc-giua-hai-mat-phang-trong-khong-gian/' => 'https://giasu.ai.vn/bai-viet/cach-tinh-goc-giua-hai-mat-phang-trong-khong-gian.html',
        '/cach-tinh-khoang-cach-tu-mot-diem-den-mot-mat-phang/' => 'https://giasu.ai.vn/bai-viet/cach-tinh-khoang-cach-tu-mot-diem-den-mot-mat-phang.html',
        '/cach-tinh-thang-du-thang-thieu-bang-ban-tay/' => 'https://giasu.ai.vn/bai-viet/cach-tinh-thang-du-thang-thieu-bang-ban-tay.html',
        '/cach-viet-50-bo-thu-thuong-dung/' => 'https://giasu.ai.vn/bai-viet/cach-viet-50-bo-thu-thuong-dung.html',
        '/cau-do-chin-diem/' => 'https://giasu.ai.vn/bai-viet/cau-do-chin-diem.html',
        '/cau-do-day-so-bi-an/' => 'https://giasu.ai.vn/bai-viet/cau-do-day-so-bi-an.html',
        '/cau-lenh-vong-lap-while-trong-python/' => 'https://giasu.ai.vn/bai-viet/cau-lenh-vong-lap-while-trong-python.html',
        '/chat-x-co-cong-thuc-phan-tu-c6h8o4-cho-1-mol-x-phan-ung-het-voi-dung-dich-naoh-thu-duoc-chat-y-va-2-mol-chat-z/' => 'https://giasu.ai.vn/bai-viet/chat-x-co-cong-thuc-phan-tu-c6h8o4-cho-1-mol-x-phan-ung-het-voi-dung-dich-naoh-thu-duoc-chat-y-va-2-mol-chat-z.html',
        '/cho-1-mol-chat-x-c9h8o4-chua-vong-benzen-tac-dung-het-voi-naoh-du-thu-duoc-2-mol-chat-y-1-mol-chat-z-va-1-mol-h2o/' => 'https://giasu.ai.vn/bai-viet/cho-1-mol-chat-x-c9h8o4-chua-vong-benzen-tac-dung-het-voi-naoh-du-thu-duoc-2-mol-chat-y-1-mol-chat-z-va-1-mol-h2o.html',
        '/cho-axit-cacboxylic-x-phan-ung-voi-chat-y-thu-duoc-mot-muoi-co-cong-thuc-phan-tu-c3h9o2n/' => 'https://giasu.ai.vn/bai-viet/cho-axit-cacboxylic-x-phan-ung-voi-chat-y-thu-duoc-mot-muoi-co-cong-thuc-phan-tu-c3h9o2n.html',
        '/cho-este-hai-chuc-mach-ho-x-c7h10o4-tac-dung-voi-luong-du-dung-dich-naoh-dun-nong-thu-duoc-ancol-y-no-hai-chuc-va-hai-muoi/' => 'https://giasu.ai.vn/bai-viet/cho-este-hai-chuc-mach-ho-x-c7h10o4-tac-dung-voi-luong-du-dung-dich-naoh-dun-nong-thu-duoc-ancol-y-no-hai-chuc-va-hai-muoi.html',
        '/chon-diem-roi-trong-bat-dang-thuc-cosi/' => 'https://giasu.ai.vn/bai-viet/chon-diem-roi-trong-bat-dang-thuc-cosi.html',
        '/chung-minh-ba-duong-thang-dong-quy-trong-khong-gian/' => 'https://giasu.ai.vn/bai-viet/chung-minh-ba-duong-thang-dong-quy-trong-khong-gian.html',
        '/chung-minh-duong-thang-song-song-voi-mat-phang/' => 'https://giasu.ai.vn/bai-viet/chung-minh-duong-thang-song-song-voi-mat-phang.html',
        '/chuyen-de-thiet-dien-trong-hinh-hoc-khong-gian/' => 'https://giasu.ai.vn/bai-viet/chuyen-de-thiet-dien-trong-hinh-hoc-khong-gian.html',
        '/co-bao-nhieu-con-meo/' => 'https://giasu.ai.vn/bai-viet/co-bao-nhieu-con-meo.html',
        '/danh-phap-cac-chat-hoa-hoc-chuong-trinh-giao-duc-pho-thong-moi-2018/' => 'https://giasu.ai.vn/bai-viet/danh-phap-cac-chat-hoa-hoc-chuong-trinh-giao-duc-pho-thong-moi-2018.html',
        '/danh-sach-300-tu-vung-hsk-1-phien-ban-moi/' => 'https://giasu.ai.vn/bai-viet/danh-sach-300-tu-vung-hsk-1-phien-ban-moi.html',
        '/dien-phan-200-ml-dung-dich-cuso4-voi-dien-cuc-tro-bang-dong-dien-mot-chieu/' => 'https://giasu.ai.vn/bai-viet/dien-phan-200-ml-dung-dich-cuso4-voi-dien-cuc-tro-bang-dong-dien-mot-chieu.html',
        '/dong-dang-hoa/' => 'https://giasu.ai.vn/bai-viet/dong-dang-hoa.html',
        '/dot-chay-hoan-toan-132-gam-este-x-thu-duoc-06-mol-co2-va-06-mol-h2o-cong-thuc-phan-tu-cua-x-la/' => 'https://giasu.ai.vn/bai-viet/dot-chay-hoan-toan-132-gam-este-x-thu-duoc-06-mol-co2-va-06-mol-h2o-cong-thuc-phan-tu-cua-x-la.html',
        '/este-x-co-cong-thuc-phan-tu-c6h10o4-xa-phong-hoa-hoan-toan-x-bang-dung-dich-naoh-thu-duoc-ba-chat-huu-co-y-z-t/' => 'https://giasu.ai.vn/bai-viet/este-x-co-cong-thuc-phan-tu-c6h10o4-xa-phong-hoa-hoan-toan-x-bang-dung-dich-naoh-thu-duoc-ba-chat-huu-co-y-z-t.html',
        '/file-luyen-viet-50-bo-thu-thuong-dung/' => 'https://giasu.ai.vn/bai-viet/file-luyen-viet-50-bo-thu-thuong-dung.html',
        '/giai-bai-tap-chat-beo-theo-phuong-phap-don-chat/' => 'https://giasu.ai.vn/bai-viet/giai-bai-tap-chat-beo-theo-phuong-phap-don-chat.html',
        '/giai-thoai-archimedes/' => 'https://giasu.ai.vn/bai-viet/giai-thoai-archimedes.html',
        '/giai-toan-tieu-hoc-bang-phuong-phap-thu-chon/' => 'https://giasu.ai.vn/bai-viet/giai-toan-tieu-hoc-bang-phuong-phap-thu-chon.html',
        '/gioi-thieu-cai-dat-python/' => 'https://giasu.ai.vn/bai-viet/gioi-thieu-cai-dat-python.html',
        '/goc-giua-hai-duong-thang-trong-khong-gian/' => 'https://giasu.ai.vn/bai-viet/goc-giua-hai-duong-thang-trong-khong-gian.html',
        '/ham-an-danh-trong-python/' => 'https://giasu.ai.vn/bai-viet/ham-an-danh-trong-python.html',
        '/ham-so-bac-hai/' => 'https://giasu.ai.vn/bai-viet/ham-so-bac-hai.html',
        '/he-thuc-luong-trong-tam-giac-lop-10/' => 'https://giasu.ai.vn/bai-viet/he-thuc-luong-trong-tam-giac-lop-10.html',
        '/hinh-chop-hinh-lang-tru-hinh-hop-la-gi/' => 'https://giasu.ai.vn/bai-viet/hinh-chop-hinh-lang-tru-hinh-hop-la-gi.html',
        '/hoa-tan-hoan-toan-2652-gam-al2o3-bang-mot-luong-vua-du-dung-dich-hno3-thu-duoc-247-gam-dung-dich-x/' => 'https://giasu.ai.vn/bai-viet/hoa-tan-hoan-toan-2652-gam-al2o3-bang-mot-luong-vua-du-dung-dich-hno3-thu-duoc-247-gam-dung-dich-x.html',
        '/hoc-nhanh-214-bo-thu-chu-han-qua-bai-tho-82-cau/' => 'https://giasu.ai.vn/bai-viet/hoc-nhanh-214-bo-thu-chu-han-qua-bai-tho-82-cau.html',
        '/hop-chat-huu-co-mach-ho-x-c8h12o5-tac-dung-voi-luong-du-dung-dich-naoh-dun-nong-thu-duoc-glixerol-va-hon-hop-2-muoi-cacboxylat-y-va-z/' => 'https://giasu.ai.vn/bai-viet/hop-chat-huu-co-mach-ho-x-c8h12o5-tac-dung-voi-luong-du-dung-dich-naoh-dun-nong-thu-duoc-glixerol-va-hon-hop-2-muoi-cacboxylat-y-va-z.html',
        '/hop-chat-huu-co-x-co-cong-thuc-phan-tu-c5h6o4-x-tac-dung-voi-naoh-trong-dung-dich-theo-ti-le-mol-1-2-tao-ra-muoi-cua-axit-no-y-va-ancol-z/' => 'https://giasu.ai.vn/bai-viet/hop-chat-huu-co-x-co-cong-thuc-phan-tu-c5h6o4-x-tac-dung-voi-naoh-trong-dung-dich-theo-ti-le-mol-1-2-tao-ra-muoi-cua-axit-no-y-va-ancol-z.html',
        '/hsk-la-gi-nhung-dieu-can-biet-ve-ky-thi-nang-luc-tieng-trung/' => 'https://giasu.ai.vn/bai-viet/hsk-la-gi-nhung-dieu-can-biet-ve-ky-thi-nang-luc-tieng-trung.html',
        '/huong-dan-lap-trinh-python-python-guilde/' => 'https://giasu.ai.vn/bai-viet/huong-dan-lap-trinh-python-python-guilde.html',
        '/khoang-cach-giua-hai-duong-thang-cheo-nhau/' => 'https://giasu.ai.vn/bai-viet/khoang-cach-giua-hai-duong-thang-cheo-nhau.html',
        '/kieu-du-lieu-list-danh-sach-trong-python/' => 'https://giasu.ai.vn/bai-viet/kieu-du-lieu-list-danh-sach-trong-python.html',
        '/kieu-xau-string-trong-python-kieu-chuoi-trong-python/' => 'https://giasu.ai.vn/bai-viet/kieu-xau-string-trong-python-kieu-chuoi-trong-python.html',
        '/luong-dien-tieu-thu-trung-binh-1-gia-dinh-la-bao-nhieu/' => 'https://giasu.ai.vn/bai-viet/luong-dien-tieu-thu-trung-binh-1-gia-dinh-la-bao-nhieu.html',
        '/ly-thuyet-va-bai-tap-dau-nhi-thuc-bac-nhat/' => 'https://giasu.ai.vn/bai-viet/ly-thuyet-va-bai-tap-dau-nhi-thuc-bac-nhat.html',
        '/ly-thuyet-va-bai-tap-dau-tam-thuc-bac-hai/' => 'https://giasu.ai.vn/bai-viet/ly-thuyet-va-bai-tap-dau-tam-thuc-bac-hai.html',
        '/ly-thuyet-va-bai-tap-dien-phan-co-loi-giai-chi-tiet/' => 'https://giasu.ai.vn/bai-viet/ly-thuyet-va-bai-tap-dien-phan-co-loi-giai-chi-tiet.html',
        '/nho-rat-tu-tu-400ml-dung-dich-hcl-05m-vao-100ml-dung-dich-hon-hop-chua-nahco3-05m-va-na2co3-1m/' => 'https://giasu.ai.vn/bai-viet/nho-rat-tu-tu-400ml-dung-dich-hcl-05m-vao-100ml-dung-dich-hon-hop-chua-nahco3-05m-va-na2co3-1m.html',
        '/nuoc-dong-bang-la-qua-trinh-toa-nhiet-hay-thu-nhiet/' => 'https://giasu.ai.vn/bai-viet/nuoc-dong-bang-la-qua-trinh-toa-nhiet-hay-thu-nhiet.html',
        '/phan-so-bang-nhau/' => 'https://giasu.ai.vn/bai-viet/phan-so-bang-nhau.html',
        '/phuong-phap-bao-toan-dien-tich/' => 'https://giasu.ai.vn/bai-viet/phuong-phap-bao-toan-dien-tich.html',
        '/phuong-phap-bao-toan-electron/' => 'https://giasu.ai.vn/bai-viet/phuong-phap-bao-toan-electron.html',
        '/phuong-phap-bao-toan-khoi-luong/' => 'https://giasu.ai.vn/bai-viet/phuong-phap-bao-toan-khoi-luong.html',
        '/phuong-phap-bao-toan-nguyen-to/' => 'https://giasu.ai.vn/bai-viet/phuong-phap-bao-toan-nguyen-to.html',
        '/phuong-phap-duong-cheo/' => 'https://giasu.ai.vn/bai-viet/phuong-phap-duong-cheo.html',
        '/phuong-phap-quy-doi/' => 'https://giasu.ai.vn/bai-viet/phuong-phap-quy-doi.html',
        '/phuong-phap-tang-giam-khoi-luong/' => 'https://giasu.ai.vn/bai-viet/phuong-phap-tang-giam-khoi-luong.html',
        '/phuong-phap-trung-binh/' => 'https://giasu.ai.vn/bai-viet/phuong-phap-trung-binh.html',
        '/phuong-phap-tu-duy-don-chat-xep-hinh-giai-bai-tap-hoa-hoc-huu-co/' => 'https://giasu.ai.vn/bai-viet/phuong-phap-tu-duy-don-chat-xep-hinh-giai-bai-tap-hoa-hoc-huu-co.html',
        '/phuong-trinh-chua-can-bat-phuong-trinh-chua-can/' => 'https://giasu.ai.vn/bai-viet/phuong-trinh-chua-can-bat-phuong-trinh-chua-can.html',
        '/phuong-trinh-chua-tri-tuyet-doi/' => 'https://giasu.ai.vn/bai-viet/phuong-trinh-chua-tri-tuyet-doi.html',
        '/present-simple/' => 'https://giasu.ai.vn/bai-viet/present-simple.html',
        '/python-lam-duoc-nhung-gi/' => 'https://giasu.ai.vn/bai-viet/python-lam-duoc-nhung-gi.html',
        '/quy-doi-este/' => 'https://giasu.ai.vn/bai-viet/quy-doi-este.html',
        '/quy-doi-peptit/' => 'https://giasu.ai.vn/bai-viet/quy-doi-peptit.html',
        '/so-sanh-1-so-voi-2-nghiem-cua-phuong-trinh-bac-hai/' => 'https://giasu.ai.vn/bai-viet/so-sanh-1-so-voi-2-nghiem-cua-phuong-trinh-bac-hai.html',
        '/so-sanh-tu-vung-hsk-moi-va-cu/' => 'https://giasu.ai.vn/bai-viet/so-sanh-tu-vung-hsk-moi-va-cu.html',
        '/thi-nghiem-mat-nuoc/' => 'https://giasu.ai.vn/bai-viet/thi-nghiem-mat-nuoc.html',
        '/thiet-dien-la-gi-va-cac-phuong-phap-tim-thiet-dien/' => 'https://giasu.ai.vn/bai-viet/thiet-dien-la-gi-va-cac-phuong-phap-tim-thiet-dien.html',
        '/thuy-phan-hoan-toan-148-gam-este-don-chuc-x-bang-dung-dich-naoh-du-dun-nong-thu-duoc-164-gam-muoi-y/' => 'https://giasu.ai.vn/bai-viet/thuy-phan-hoan-toan-148-gam-este-don-chuc-x-bang-dung-dich-naoh-du-dun-nong-thu-duoc-164-gam-muoi-y.html',
        '/tien-hanh-san-xuat-ruou-vang-bang-phuong-phap-len-men-ruou-voi-nguyen-lieu-la-168-kg-qua-nho-tuoi-chua-15-glucozo-ve-khoi-luong/' => 'https://giasu.ai.vn/bai-viet/tien-hanh-san-xuat-ruou-vang-bang-phuong-phap-len-men-ruou-voi-nguyen-lieu-la-168-kg-qua-nho-tuoi-chua-15-glucozo-ve-khoi-luong.html',
        '/tim-dieu-kien-de-tam-thuc-bac-hai-luon-duong/' => 'https://giasu.ai.vn/bai-viet/tim-dieu-kien-de-tam-thuc-bac-hai-luon-duong.html',
        '/toc-do-chuyen-dong/' => 'https://giasu.ai.vn/bai-viet/toc-do-chuyen-dong.html',
        '/tong-hop-1500-chu-han-pho-bien-nhat-trong-tieng-trung/' => 'https://giasu.ai.vn/bai-viet/tong-hop-1500-chu-han-pho-bien-nhat-trong-tieng-trung.html',
        '/tong-hop-23-phuong-phap-giai-bai-tap-mon-hoa-hoc/' => 'https://giasu.ai.vn/bai-viet/tong-hop-23-phuong-phap-giai-bai-tap-mon-hoa-hoc.html',
        '/tong-hop-50-bai-tap-chat-beo-co-loi-giai-chi-tiet/' => 'https://giasu.ai.vn/bai-viet/tong-hop-50-bai-tap-chat-beo-co-loi-giai-chi-tiet.html',
        '/tong-hop-bai-tap-huu-co-hay-va-kho/' => 'https://giasu.ai.vn/bai-viet/tong-hop-bai-tap-huu-co-hay-va-kho.html',
        '/tong-hop-bai-tap-phuong-phap-don-chat-xep-hinh/' => 'https://giasu.ai.vn/bai-viet/tong-hop-bai-tap-phuong-phap-don-chat-xep-hinh.html',
        '/tong-hop-cac-chuyen-de-hoa-hoc-lop-10/' => 'https://giasu.ai.vn/bai-viet/tong-hop-cac-chuyen-de-hoa-hoc-lop-10.html',
        '/tong-hop-cac-chuyen-de-hoa-hoc-lop-11/' => 'https://giasu.ai.vn/bai-viet/tong-hop-cac-chuyen-de-hoa-hoc-lop-11.html',
        '/tong-hop-cac-chuyen-de-hoa-hoc-lop-12/' => 'https://giasu.ai.vn/bai-viet/tong-hop-cac-chuyen-de-hoa-hoc-lop-12.html',
        '/tong-hop-ki-thuat-phuong-phap-giai-bai-tap-peptit-day-du-chi-tiet/' => 'https://giasu.ai.vn/bai-viet/tong-hop-ki-thuat-phuong-phap-giai-bai-tap-peptit-day-du-chi-tiet.html',
        '/tong-hop-thi-nghiem-este-chat-beo-hay-va-kho-co-dap-an-chi-tiet/' => 'https://giasu.ai.vn/bai-viet/tong-hop-thi-nghiem-este-chat-beo-hay-va-kho-co-dap-an-chi-tiet.html',
        '/trong-binh-kin-dung-tich-khong-doi-chua-hon-hop-khi-x-gom-h2-va-n2-chat-xuc-tac-thich-hop/' => 'https://giasu.ai.vn/bai-viet/trong-binh-kin-dung-tich-khong-doi-chua-hon-hop-khi-x-gom-h2-va-n2-chat-xuc-tac-thich-hop.html',
        '/tu-khoa-and-trong-python-de-lam-gi/' => 'https://giasu.ai.vn/bai-viet/tu-khoa-and-trong-python-de-lam-gi.html',
        '/tu-m-kg-mun-cua-chua-50-xenlulozo-con-lai-la-tap-chat-tro-san-xuat-duoc-80-kg-glucozo-voi-hieu-suat-toan-bo-qua-trinh-la-80-gia-tri-cua-m-la/' => 'https://giasu.ai.vn/bai-viet/tu-m-kg-mun-cua-chua-50-xenlulozo-con-lai-la-tap-chat-tro-san-xuat-duoc-80-kg-glucozo-voi-hieu-suat-toan-bo-qua-trinh-la-80-gia-tri-cua-m-la.html',
        '/viet-doan-van-cam-nhan/' => 'https://giasu.ai.vn/bai-viet/viet-doan-van-cam-nhan.html',
        '/vo-ghi-bai-hoc-hoa-11-kntt-ca-nam/' => 'https://giasu.ai.vn/bai-viet/vo-ghi-bai-hoc-hoa-11-kntt-ca-nam.html',
        '/xac-suat-tung-dong-xu/' => 'https://giasu.ai.vn/bai-viet/xac-suat-tung-dong-xu.html',
    ];

    $request_path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
    $trimmed_path = rtrim($request_path, '/');

    foreach ($redirects as $old_path => $target_url) {
        if (rtrim($old_path, '/') === $trimmed_path) {
            wp_redirect($target_url, 301);
            exit;
        }
    }
});
