const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const languages={vi:'Tiếng Việt',en:'Tiếng Anh','vi-en':'Song ngữ Việt–Anh'};
export function renderExamCatalog(exams){
 const select=(key,label,values)=>`<label class="exam-filter">${label}<select id="exam-${key}" data-filter="${key}"><option value="">Tất cả</option>${values.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select></label>`;
 const values=key=>[...new Set(exams.map(e=>e[key]).filter(Boolean))].sort((a,b)=>key==='year'?b-a:String(a).localeCompare(String(b),'vi')).map(v=>[v,v]);
 const topics=[...new Set(exams.flatMap(e=>e.tags||[]))].sort((a,b)=>a.localeCompare(b,'vi')).map(v=>[v,v]);
 const cards=exams.map(e=>`<article class="card exam-card" data-slug="${esc(e.slug)}"><div class="card-content"><div class="eyebrow">${e.exam_group==='quốc tế'?'Toán quốc tế':'Đề Việt Nam'} · ${esc(e.competition||e.category)}</div><h2><a href="./${esc(e.slug)}.html">${esc(e.title)}</a></h2><p>${e.questions.length} câu · ${e.duration} phút${e.year?` · ${e.year}`:''}</p><p>${esc(e.level||(e.grade?'Lớp '+e.grade:'Mọi cấp độ'))} · ${languages[e.language]||languages.vi}</p><p>${e.mode==='self-review'?'Tự luyện chứng minh · tự đối chiếu lời giải':e.questions.every(q=>q.answer!==null)?'Có đáp án và chấm điểm':'Tự luyện · chưa đủ đáp án'}</p><p>${e.questions.some(q=>q.solution.trim())?'Có lời giải tham khảo':'Chưa có lời giải'}</p><a class="primary" href="./${esc(e.slug)}.html">${e.mode==='self-review'?'Bắt đầu tự luyện':'Làm bài'} →</a></div></article>`).join('');
 const data=exams.map(({questions,...e})=>e);
 return `<main id="main" class="wrap library"><div class="section-heading"><div><span class="overline">TỰ LUYỆN MỖI NGÀY</span><h1>Đề kiểm tra</h1></div></div><div class="exam-groups" role="group" aria-label="Nhóm đề"><button data-group="" aria-pressed="true" class="active">Tất cả</button><button data-group="việt nam" aria-pressed="false">Đề Việt Nam</button><button data-group="quốc tế" aria-pressed="false">Toán quốc tế</button></div><label class="search"><input id="exam-search" type="search" placeholder="Tìm tên đề, kỳ thi, chủ đề…" aria-label="Tìm đề kiểm tra"></label><div class="exam-filters">${select('competition','Kỳ thi',values('competition'))}${select('year','Năm',values('year'))}${select('level','Cấp độ kỳ thi',values('level'))}${select('language','Ngôn ngữ',Object.entries(languages))}${select('grade','Lớp Việt Nam (nếu có)',Array.from({length:12},(_,i)=>[i+1,'Lớp '+(i+1)]))}${select('category','Môn học',values('category'))}${select('tag','Chủ đề',topics)}</div><p id="exam-count" role="status">${exams.length} đề kiểm tra</p><button id="exam-reset" class="quiz-reset">Xóa bộ lọc</button><div class="cards">${cards}</div><p id="exam-empty" hidden>Chưa có đề phù hợp. Thử bỏ bớt bộ lọc hoặc quay lại sau khi có đề mới.</p><noscript><p>Bật JavaScript để lọc; bạn vẫn có thể mở các đề bên trên.</p></noscript></main><script id="exam-catalog-data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script type="module" src="../assets/exam-list.js"></script>`;
}
