import {createHash} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function buildExams(imported,out,shell,markdown){
 const exams=imported.map(p=>p.exam).filter(e=>e.questions.length);
 fs.mkdirSync(path.join(out,'de-kiem-tra'),{recursive:true});
 for(const e of exams){
  const rendered={...e,questions:e.questions.map(q=>({...q,question:markdown(q.question),options:q.options.map(o=>markdown(o)),solution:markdown(q.solution)}))};
  rendered.version=createHash('sha256').update(JSON.stringify(rendered)).digest('hex').slice(0,16);
  const missing=e.questions.filter(q=>q.answer===null).length;
  const body=`<main id="main" class="wrap exam-wrap"><a class="back" href="./">← Danh sách đề kiểm tra</a><h1>${esc(e.title)}</h1><p>${e.questions.length} câu · ${e.duration} phút · ${esc(e.category)}${e.grade?` · Lớp ${e.grade}`:''}</p><p class="exam-policy">Tự luyện: mỗi câu có trọng số bằng nhau; câu đúng/sai tính theo tỉ lệ ý đúng. Tổng điểm quy đổi về thang 10.</p>${missing?`<p class="exam-warning">Đề còn ${missing} câu chưa có đáp án. Bạn vẫn có thể làm bài, nhưng chưa có tổng điểm. Các câu thiếu đáp án sẽ ghi “Chưa có đáp án”.</p>`:''}<section id="exam-start" class="quiz"><h2>Sẵn sàng làm bài?</h2><p>Thời gian bắt đầu khi bạn bấm nút bên dưới. Bài đang làm được lưu trên trình duyệt này.</p><button class="primary" id="start-exam">Bắt đầu làm bài</button></section><p id="storage-warning" role="status" hidden>Trình duyệt không cho phép lưu bài. Đừng đóng hoặc tải lại trang khi đang làm.</p><section id="exam-session" hidden><div class="exam-toolbar"><strong id="exam-timer" role="timer" aria-label="Thời gian còn lại"></strong><span id="exam-progress"></span><button class="primary" id="submit-exam">Nộp bài</button></div><nav id="exam-nav" aria-label="Chuyển nhanh đến câu hỏi"></nav><div id="exam-questions"></div></section><section id="exam-result" class="quiz" hidden tabindex="-1"><h2>Kết quả bài làm</h2><p id="score" role="status"></p><p id="elapsed"></p><button id="restart-exam" class="primary">Làm lại đề</button><a class="back" href="../bai-viet/${e.slug}.html">Xem bản đề</a></section><noscript>Bật JavaScript để làm bài kiểm tra.</noscript></main><script type="application/json" id="exam-data">${JSON.stringify(rendered).replace(/</g,'\\u003c')}</script><script type="module" src="../assets/exam.js"></script>`;
  fs.writeFileSync(path.join(out,'de-kiem-tra',e.slug+'.html'),shell(e.title,'Làm đề kiểm tra trực tuyến và xem lời giải.',body,'../'));
 }
 const body=`<main id="main" class="wrap library"><div class="section-heading"><div><span class="overline">TỰ LUYỆN MỖI NGÀY</span><h1>Đề kiểm tra</h1></div></div><div class="filter-bar"><label class="search"><input id="exam-search" type="search" placeholder="Tìm tên đề…" aria-label="Tìm đề kiểm tra"></label><select id="exam-grade" aria-label="Lọc đề theo lớp"><option value="">Tất cả lớp</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}">Lớp ${i+1}</option>`).join('')}</select><select id="exam-category" aria-label="Lọc đề theo môn"><option value="">Tất cả môn</option>${[...new Set(exams.map(e=>e.category))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><p id="exam-count" role="status">${exams.length} đề kiểm tra</p><div class="cards">${exams.map(e=>`<article class="card exam-card" data-grade="${e.grade||''}" data-category="${esc(e.category)}"><div class="card-content"><div class="eyebrow">${esc(e.category)} · ${e.grade?'Lớp '+e.grade:'Mọi lớp'}</div><h2><a href="./${e.slug}.html">${esc(e.title)}</a></h2><p>${e.questions.length} câu · ${e.duration} phút</p><p>${e.questions.every(q=>q.answer!==null)?'Có đáp án và chấm điểm':'Tự luyện · chưa đủ đáp án'}</p><a class="primary" href="./${e.slug}.html">Làm bài →</a></div></article>`).join('')}</div><p id="exam-empty" hidden>Chưa có đề phù hợp với bộ lọc.</p></main><script type="module" src="../assets/exam-list.js"></script>`;
 fs.writeFileSync(path.join(out,'de-kiem-tra/index.html'),shell('Đề kiểm tra','Kho đề tự luyện theo môn học và lớp.',body,'../'));
}
