import {extraGamesHTML} from './extra-games.mjs';
import {waterHTML} from './water-art.mjs';
import {riverHTML} from './river-art.mjs';
export const gamesHTML=`<p>Những trò chơi nhỏ để thư giãn và luyện tư duy. Chơi ngay trên trình duyệt.</p>
<div class="game-tabs" role="group" aria-label="Chọn trò chơi"><button data-game="numbers" aria-pressed="true">2048</button><button data-game="river" aria-pressed="false">Sói · Dê · Bắp cải</button><button data-game="water" aria-pressed="false">Đong nước</button><button data-game="sudoku" aria-pressed="false">Sudoku</button><button data-game="hanoi" aria-pressed="false">Tháp Hà Nội</button><button data-game="tangram" aria-pressed="false">Tangram</button><button data-game="words" aria-pressed="false">Đoán từ</button></div>
<section class="game-panel" id="game-numbers"><div class="game-title-row"><h2>2048</h2><button type="button" class="game-sound" data-puzzle-sound aria-label="Tắt âm thanh"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/></svg></button></div><p>Ghép hai ô cùng số để đạt 2048. Dùng phím mũi tên khi chọn bàn chơi, vuốt trên bàn hoặc bấm nút bên dưới.</p><p>Điểm: <strong id="game-score">0</strong></p><div id="number-scene" class="number-scene"><div id="number-board" class="number-board" tabindex="0" role="group" aria-label="Bàn chơi 2048, dùng phím mũi tên"></div></div><div class="game-directions" role="group" aria-label="Di chuyển"><button data-direction="left" aria-label="Sang trái">←</button><button data-direction="up" aria-label="Lên trên">↑</button><button data-direction="down" aria-label="Xuống dưới">↓</button><button data-direction="right" aria-label="Sang phải">→</button></div><p id="number-status" role="status"></p><button data-restart="numbers">Chơi lại</button></section>
${riverHTML}
${waterHTML}
<section class="game-panel" id="game-words" tabindex="0" hidden><div class="game-title-row"><h2>Đoán từ tiếng Anh</h2><button type="button" class="game-sound" data-puzzle-sound aria-label="Tắt âm thanh"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/></svg></button></div><details class="word-help"><summary>Luật chơi · 5 chữ, 6 lượt</summary><p>Đoán từ gồm 5 chữ cái trong 6 lượt. Bộ từ cơ bản dành cho học sinh. Xanh lá: đúng vị trí; vàng: có trong từ nhưng sai vị trí; xám: không có hoặc đã đủ số lần xuất hiện.</p></details><div id="word-board" class="word-board" aria-label="Các lượt đoán"></div><div id="word-keyboard" class="word-keyboard" role="group" aria-label="Bàn phím đoán từ"></div><p class="word-hint">Bấm bàn phím bên dưới hoặc gõ trực tiếp. ↵ gửi từ · ⌫ xoá chữ.</p><p id="word-status" role="status"></p><button id="word-give-up" type="button">Bỏ cuộc · xem đáp án</button><button data-restart="words">Từ mới</button></section>
${extraGamesHTML}
<section class="game-panel" id="game-tangram" hidden><div class="game-title-row"><h2>Ghép hình Tangram</h2></div><p>Bảy mảnh được cắt từ một hình vuông: hai tam giác lớn, một tam giác vừa, hai tam giác nhỏ, một hình vuông và một hình bình hành. Kéo, xoay hoặc lật các mảnh để lấp đầy hình bóng.</p><div id="tangram-scene"><div class="scene-tools tangram-level-tools"><button type="button" id="tangram-prev" aria-label="Màn trước" title="Màn trước">←</button><span id="tangram-level-label" aria-live="polite"></span><button type="button" id="tangram-reset" aria-label="Chơi lại màn này" title="Chơi lại">↻</button><button type="button" id="tangram-next" aria-label="Màn tiếp theo" title="Màn tiếp theo">→</button></div><svg id="tangram-board" viewBox="0 0 620 560" role="group" aria-label="Bàn ghép hình Tangram"></svg></div><div class="tangram-actions"><button type="button" id="tangram-left" aria-label="Xoay mảnh sang trái">↶ Xoay trái</button><button type="button" id="tangram-right" aria-label="Xoay mảnh sang phải">Xoay phải ↷</button><button type="button" id="tangram-flip" aria-label="Lật mảnh được chọn">Lật mảnh</button><button type="button" id="tangram-hint" aria-pressed="false">Hiện đường ghép</button></div><p id="tangram-status" role="status"></p></section>
<noscript>Bật JavaScript để chơi các trò chơi.</noscript><script type="module" src="../assets/games.js"></script><script type="module" src="../assets/tangram.js"></script>`;
