import fs from 'node:fs';
const source=fs.readFileSync(new URL('../assets/wolf cabbage sheep.svg',import.meta.url),'utf8');
const boxes={farmer:'0 0 120 165',wolf:'-12 20 175 155',sheep:'20 15 150 145',cabbage:'10 20 100 100',boat:'0 0 350 100',oar:'0 0 165 25','bank-left':'0 0 225 155','bank-right':'25 -45 220 200',river:'0 0 370 120'};
const symbols=Object.entries(boxes).map(([name,box])=>{
 const group=source.match(new RegExp(`<g id="element-${name}"[^>]*>([\\s\\S]*?)<\\/g>`));
 if(!group)throw Error(`Thiếu hình ${name} trong wolf cabbage sheep.svg`);
 let content=group[1].replace(/<text\b[^>]*>[\s\S]*?<\/text>/g,'');
 if(name.startsWith('bank-'))content=content.replace(/#27ae60|#2ecc71/g,'#c3b783').replace(/#d35400/g,'#998365').replace(/#1e8449/g,'#788c68');
 if(name==='cabbage')content=content.replace(/#27ae60/g,'#378349').replace(/#2ecc71/g,'#78ce58');
 return `<symbol id="river-art-${name}" viewBox="${box}"${name==='river'||name.startsWith('bank-')?' preserveAspectRatio="none"':''}>${content}</symbol>`;
}).join('');
export const riverHTML=`<svg class="river-symbols" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"><defs>${symbols}</defs></svg>
<section class="game-panel" id="game-river" hidden><div class="river-heading"><div><span class="overline">THỬ TÀI QUA SÔNG</span><h2>Sói, Dê và Bắp cải</h2></div><span class="river-counter" id="river-steps">0 lượt</span></div><p id="river-mission"></p><p class="river-intro">Bấm nhân vật để lên hoặc xuống thuyền, bấm thuyền để qua sông. Đừng để sói ở riêng với dê, hoặc dê ở riêng với bắp cải!</p>
<div class="river-world" data-side="0"><p id="river-status" class="scene-guidance" role="status" aria-live="polite"></p><div class="scene-tools"><button type="button" data-puzzle-sound aria-label="Tắt âm thanh"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/></svg></button><button type="button" id="river-prev" aria-label="Thử thách trước" title="Thử thách trước">←</button><button type="button" data-restart="river" aria-label="Chơi lại màn qua sông" title="Chơi lại">↻</button><button type="button" id="river-next" aria-label="Màn qua sông tiếp theo" title="Thử thách tiếp theo">→</button></div><svg class="river-landscape" viewBox="0 0 900 400" preserveAspectRatio="none" aria-hidden="true"><rect width="900" height="400" fill="#e5f5f2"/><use href="#river-art-river" x="0" y="175" width="900" height="225" preserveAspectRatio="none"/><use href="#river-art-bank-left" x="0" y="0" width="290" height="330" preserveAspectRatio="none"/><use href="#river-art-bank-right" x="610" y="0" width="290" height="330" preserveAspectRatio="none"/></svg>
<section class="river-bank bank-left"><div id="river-left" class="river-characters"></div></section><section class="river-bank bank-right"><div id="river-right" class="river-characters"></div></section>
<div class="river-vessel"><button type="button" id="river-cross" class="river-boat-hit" aria-label="Bấm thuyền để qua sông"></button><svg class="river-farmer" aria-hidden="true"><use href="#river-art-farmer"/></svg><div id="river-cargo"></div><svg class="river-boat" aria-hidden="true"><use href="#river-art-boat"/></svg><span class="river-ripples" aria-hidden="true"><i></i><i></i><i></i></span><svg class="river-oar" aria-hidden="true"><use href="#river-art-oar"/></svg></div></div>
</section>`;
