import fs from 'node:fs';
const source=fs.readFileSync(new URL('../assets/water_riddle.svg',import.meta.url),'utf8');
const face=source.match(/<g id="face-happy">([\s\S]*?)<\/g>/)?.[1];
if(!face)throw Error('water_riddle.svg: thiếu face-happy');
function jug(cap,index){
 const found=source.match(new RegExp(`<g id="jug-${cap}l"[^>]*>([\\s\\S]*?)<\\/g>`));
 if(!found)throw Error(`water_riddle.svg: thiếu can ${cap} lít`);
 let art=found[1].replace(/<rect\b[^>]*class="card-box"[^>]*\/>/g,'').replace(/<text\b[^>]*>[\s\S]*?<\/text>/g,'').replace(/<line\b[^>]*class="mark-line"[^>]*\/>/g,'').replace(/href="#face-happy"/g,'href="#water-face"');
 art=art.replace(/<use href="#water-face" x="([\d.]+)" y="([\d.]+)"\/>/g,(_,x,y)=>`<g transform="translate(${x} ${y})">${face}</g>`);
 const glass=art.match(/<rect x="15" y="15" width="(\d+)" height="(\d+)" class="jug-glass"/);
 const width=Number(glass[1])-6,height=Number(glass[2])-6,bottom=18+height;
 art=art.replace(/class="jug-glass"/, 'class="jug-glass" rx="8" ry="8"');
 art=art.replace(/(<rect\b[^>]*class="jug-glass"[^>]*\/>)/,`$1<rect data-water-fill="${index}" data-bottom="${bottom}" data-height="${height}" x="18" y="${bottom}" width="${width}" height="0" rx="5" ry="5" class="water"/>`);
 return `<button type="button" class="water-jug" data-jug="${index}" aria-label="Chọn can ${cap} lít" aria-pressed="false"><svg viewBox="-22 0 ${width+50} ${bottom+38}" aria-hidden="true">${art}<text class="jug-on-can" data-water-volume x="${18+width/2}" y="${bottom-12}" text-anchor="middle">0 lít</text><text class="jug-below-can" x="${18+width/2}" y="${bottom+25}" text-anchor="middle">${cap} lít</text></svg></button>`;
}
export const waterHTML=`${[1,2,3,4,5,8,10].map(cap=>`<template id="jug-template-${cap}">${jug(cap,0)}</template>`).join('')}<svg class="river-symbols" aria-hidden="true"><defs><g id="water-face">${face}</g></defs></svg><section class="game-panel" id="game-water" hidden><div class="river-heading"><div><span class="overline">THỬ TÀI ĐONG NƯỚC</span><h2>Thử tài đong nước</h2></div><span class="river-counter" id="water-steps">0 lượt</span></div><p id="water-mission"></p><p class="puzzle-instructions">Chọn can → bấm vòi để đổ đầy, bấm can kia để rót sang, hoặc bấm cống để đổ hết. Mỗi lần rót chỉ dừng khi can nguồn hết hoặc can nhận đầy.</p><div class="water-world"><div class="scene-tools"><button type="button" data-puzzle-sound aria-label="Tắt âm thanh"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/></svg></button><button type="button" id="water-prev" aria-label="Thử thách trước" title="Thử thách trước">←</button><button type="button" data-restart="water" aria-label="Chơi lại màn nước" title="Chơi lại">↻</button><button type="button" id="water-next" aria-label="Màn nước tiếp theo" title="Thử thách tiếp theo">→</button></div><div class="water-fixtures"><button type="button" id="water-tap" class="water-fixture" aria-label="Đổ đầy can đã chọn"><svg viewBox="0 0 140 110" aria-hidden="true"><path d="M15 70V43H98Q116 43 116 64V74H92V66H39V70Z" fill="#84a6b5" stroke="#365b6f" stroke-width="4"/><path d="M65 42V23M44 20H87" stroke="#365b6f" stroke-width="9" stroke-linecap="round"/><path d="M104 79Q86 106 104 106Q122 106 104 79" fill="#2bcbba"/></svg></button><p id="water-status" class="scene-guidance" role="status" aria-live="polite"></p><button type="button" id="water-drain" class="water-fixture" aria-label="Đổ hết nước trong can đã chọn"><svg viewBox="0 0 140 110" aria-hidden="true"><ellipse cx="70" cy="75" rx="51" ry="23" fill="#bed5d7" stroke="#426c72" stroke-width="4"/><path d="M37 68L101 83M48 59L110 74M31 78L83 91" stroke="#426c72" stroke-width="5" stroke-linecap="round"/><path d="M70 16Q49 49 70 49Q91 49 70 16" fill="#2bcbba"/></svg></button></div><div class="water-jugs"></div><svg id="water-stream" aria-hidden="true"><path class="stream-body"/><path class="stream-highlight"/><g class="stream-landing"><ellipse rx="14" ry="4"/><ellipse rx="8" ry="3"/><circle r="2" cx="-7" cy="-7"/><circle r="2" cx="7" cy="-10"/></g></svg></div></section>`;
